version: '3.9'
services:
  backend:
    container_name: backend
    build: .
    ports:
      - 3001:3001
    working_dir: app-backend
    command: run dev 
    volumes: 
      - ./src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_PORT=${APP_PORT}
      JWT_SECRET=${JWT_SECRET}
      GEMINI_API_KEY=${GEMINI_API_KEY}
      DB_USER=${DB_USER}
      DB_PASS=${DB_PASS}
      DB_HOST=${DB_HOST}
      DB_PORT=${DB_PORT}
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
